export interface FoodItem {
  id: string
  name: string
  description: string
  price: number
  image?: string
  isVegetarian: boolean
  isSpicy: boolean
  region: string
  category: string
  rating: number
  numRatings: number
  ingredients: string
}

export const streetFoodData = {
  chaat: [
    {
      id: "c1",
      name: "Pani Puri",
      description: "Hollow crispy puris filled with spicy potato mixture and tangy tamarind water",
      price: 80,
      image: "/placeholder.svg?height=400&width=600&text=Pani+Puri",
      isVegetarian: true,
      isSpicy: true,
      region: "North India",
      category: "chaat",
      rating: 4.8,
      numRatings: 245,
      ingredients: "Semolina puris, potato, chickpeas, onions, tamarind water, mint, coriander, spices",
    },
    {
      id: "c2",
      name: "Aloo Tikki",
      description: "Crispy potato patties served with chickpea curry, yogurt, and chutneys",
      price: 90,
      image: "/placeholder.svg?height=400&width=600&text=Aloo+Tikki",
      isVegetarian: true,
      isSpicy: false,
      region: "Delhi",
      category: "chaat",
      rating: 4.5,
      numRatings: 187,
      ingredients: "Potatoes, peas, ginger, green chilies, coriander, spices, chickpea curry, yogurt, tamarind chutney",
    },
    {
      id: "c3",
      name: "Bhel Puri",
      description: "Puffed rice, vegetables, and tangy tamarind sauce mixed to perfection",
      price: 70,
      image: "/placeholder.svg?height=400&width=600&text=Bhel+Puri",
      isVegetarian: true,
      isSpicy: true,
      region: "Mumbai",
      category: "chaat",
      rating: 4.6,
      numRatings: 203,
      ingredients: "Puffed rice, sev, onions, tomatoes, potatoes, tamarind chutney, mint chutney, coriander",
    },
    {
      id: "c4",
      name: "Dahi Puri",
      description: "Crispy puris topped with potatoes, yogurt, and various chutneys",
      price: 85,
      image: "/placeholder.svg?height=400&width=600&text=Dahi+Puri",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.7,
      numRatings: 176,
      ingredients: "Puris, potatoes, yogurt, tamarind chutney, mint chutney, sev, coriander, spices",
    },
    {
      id: "c5",
      name: "Samosa Chaat",
      description: "Crushed samosas topped with chickpea curry, yogurt, and chutneys",
      price: 100,
      image: "/placeholder.svg?height=400&width=600&text=Samosa+Chaat",
      isVegetarian: true,
      isSpicy: true,
      region: "North India",
      category: "chaat",
      rating: 4.9,
      numRatings: 231,
      ingredients: "Samosas, chickpea curry, yogurt, tamarind chutney, mint chutney, onions, tomatoes, spices",
    },
  ],
  rolls: [
    {
      id: "r1",
      name: "Kathi Roll",
      description: "Paratha wrapped around spiced chicken or paneer with onions and chutney",
      price: 120,
      image: "/placeholder.svg?height=400&width=600&text=Kathi+Roll",
      isVegetarian: false,
      isSpicy: true,
      region: "Kolkata",
      category: "rolls",
      rating: 4.7,
      numRatings: 198,
      ingredients: "Paratha, chicken/paneer, bell peppers, onions, spices, egg, chutneys",
    },
    {
      id: "r2",
      name: "Paneer Tikka Roll",
      description: "Soft rumali roti filled with marinated and grilled paneer tikka",
      price: 110,
      image: "/placeholder.svg?height=400&width=600&text=Paneer+Tikka+Roll",
      isVegetarian: true,
      isSpicy: true,
      region: "Punjab",
      category: "rolls",
      rating: 4.5,
      numRatings: 156,
      ingredients: "Rumali roti, paneer, yogurt, bell peppers, onions, spices, mint chutney",
    },
    {
      id: "r3",
      name: "Chicken Frankie",
      description: "Spiced chicken wrapped in a thin flatbread with special masala",
      price: 130,
      image: "/placeholder.svg?height=400&width=600&text=Chicken+Frankie",
      isVegetarian: false,
      isSpicy: true,
      region: "Mumbai",
      category: "rolls",
      rating: 4.8,
      numRatings: 212,
      ingredients: "Flatbread, chicken, onions, bell peppers, spices, frankie masala, chutneys",
    },
  ],
  curries: [
    {
      id: "cu1",
      name: "Pav Bhaji",
      description: "Spicy mashed vegetable curry served with buttered bread rolls",
      price: 110,
      image: "/placeholder.svg?height=400&width=600&text=Pav+Bhaji",
      isVegetarian: true,
      isSpicy: true,
      region: "Mumbai",
      category: "curries",
      rating: 4.9,
      numRatings: 267,
      ingredients: "Potatoes, peas, tomatoes, onions, bell peppers, pav bhaji masala, butter, bread rolls",
    },
    {
      id: "cu2",
      name: "Chole Bhature",
      description: "Spicy chickpea curry served with deep-fried bread",
      price: 120,
      image: "/placeholder.svg?height=400&width=600&text=Chole+Bhature",
      isVegetarian: true,
      isSpicy: true,
      region: "Punjab",
      category: "curries",
      rating: 4.8,
      numRatings: 243,
      ingredients: "Chickpeas, tomatoes, onions, spices, bhature (deep-fried bread), coriander",
    },
    {
      id: "cu3",
      name: "Vada Pav",
      description: "Spicy potato fritter in a bun with chutneys",
      price: 50,
      image: "/placeholder.svg?height=400&width=600&text=Vada+Pav",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 4.7,
      numRatings: 289,
      ingredients: "Potatoes, gram flour, spices, bread bun, garlic chutney, green chutney",
    },
  ],
  sweets: [
    {
      id: "s1",
      name: "Jalebi",
      description: "Deep-fried pretzel-shaped sweets soaked in sugar syrup",
      price: 60,
      image: "/placeholder.svg?height=400&width=600&text=Jalebi",
      isVegetarian: true,
      isSpicy: false,
      region: "North India",
      category: "sweets",
      rating: 4.6,
      numRatings: 178,
      ingredients: "All-purpose flour, yogurt, sugar syrup, saffron, cardamom",
    },
    {
      id: "s2",
      name: "Kulfi",
      description: "Traditional Indian ice cream in various flavors",
      price: 70,
      image: "/placeholder.svg?height=400&width=600&text=Kulfi",
      isVegetarian: true,
      isSpicy: false,
      region: "North India",
      category: "sweets",
      rating: 4.8,
      numRatings: 201,
      ingredients: "Milk, sugar, pistachios, almonds, cardamom, saffron",
    },
    {
      id: "s3",
      name: "Gulab Jamun",
      description: "Deep-fried milk solids soaked in rose-flavored sugar syrup",
      price: 80,
      image: "/placeholder.svg?height=400&width=600&text=Gulab+Jamun",
      isVegetarian: true,
      isSpicy: false,
      region: "All India",
      category: "sweets",
      rating: 4.9,
      numRatings: 234,
      ingredients: "Milk powder, all-purpose flour, sugar syrup, cardamom, rose water",
    },
  ],
  beverages: [
    {
      id: "b1",
      name: "Masala Chai",
      description: "Spiced tea with milk and aromatic spices",
      price: 30,
      image: "/placeholder.svg?height=400&width=600&text=Masala+Chai",
      isVegetarian: true,
      isSpicy: false,
      region: "All India",
      category: "beverages",
      rating: 4.7,
      numRatings: 312,
      ingredients: "Tea leaves, milk, ginger, cardamom, cinnamon, cloves, sugar",
    },
    {
      id: "b2",
      name: "Lassi",
      description: "Yogurt-based sweet or savory drink with various flavors",
      price: 60,
      image: "/placeholder.svg?height=400&width=600&text=Lassi",
      isVegetarian: true,
      isSpicy: false,
      region: "Punjab",
      category: "beverages",
      rating: 4.6,
      numRatings: 187,
      ingredients: "Yogurt, sugar/salt, water, cardamom, saffron (for sweet lassi)",
    },
    {
      id: "b3",
      name: "Nimbu Pani",
      description: "Refreshing lemonade with a hint of salt and spices",
      price: 40,
      image: "/placeholder.svg?height=400&width=600&text=Nimbu+Pani",
      isVegetarian: true,
      isSpicy: false,
      region: "All India",
      category: "beverages",
      rating: 4.5,
      numRatings: 156,
      ingredients: "Lemon juice, water, sugar, salt, cumin powder, mint leaves",
    },
  ],
}
