export interface FoodItem {
  id: string;
  name: string;
  description: string;
  price: number;
  image?: string;
  isVegetarian: boolean;
  isSpicy: boolean;
  region: string;
  category: string;
  rating: number;
  numRatings: number;
  ingredients: string;
}

export const streetFoodData = {
  chaat: [
    {
      id: "c1",
      name: "Pani Puri",
      description:
        "Hollow crispy puris filled with spicy potato mixture and tangy tamarind water. A beloved street snack, especially popular in Maharashtra's Amravati, offering a burst of flavors in every bite.",
      price: 40,
      image: "/placeholder.svg?height=400&width=600&text=Pani+Puri",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.9,
      numRatings: 245,
      ingredients:
        "Semolina puris, potato, chickpeas, onions, tamarind water, mint, coriander, spices",
    },
    {
      id: "c2",
      name: "Aloo Tikki",
      description:
        "Crispy potato patties served with chickpea curry, yogurt, and chutneys. A favorite in Amravati, Maharashtra, known for its rich, tangy, and spicy flavors.",
      price: 50,
      image: "/placeholder.svg?height=400&width=600&text=Aloo+Tikki",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.2,
      numRatings: 187,
      ingredients:
        "Potatoes, peas, ginger, green chilies, coriander, spices, chickpea curry, yogurt, tamarind chutney",
    },
    {
      id: "c3",
      name: "Bhel Puri",
      description:
        "Puffed rice, vegetables, and tangy tamarind sauce mixed to perfection. A staple street food in Amravati, Maharashtra, offering a crunchy, spicy, and refreshing taste.",
      price: 35,
      image: "/placeholder.svg?height=400&width=600&text=Bhel+Puri",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.5,
      numRatings: 203,
      ingredients:
        "Puffed rice, sev, onions, tomatoes, potatoes, tamarind chutney, mint chutney, coriander",
    },
    {
      id: "c4",
      name: "Dahi Puri",
      description:
        "Crispy puris topped with potatoes, yogurt, and various chutneys. A cooling, flavorful treat popular in Amravati, Maharashtra, especially during hot summer evenings.",
      price: 45,
      image: "/placeholder.svg?height=400&width=600&text=Dahi+Puri",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.3,
      numRatings: 176,
      ingredients:
        "Puris, potatoes, yogurt, tamarind chutney, mint chutney, sev, coriander, spices",
    },
    {
      id: "c5",
      name: "Samosa Chaat",
      description:
        "Crushed samosas topped with chickpea curry, yogurt, and chutneys. A hearty, spicy street food favorite in Amravati, Maharashtra, perfect for evening snacks.",
      price: 60,
      image: "/placeholder.svg?height=400&width=600&text=Samosa+Chaat",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.1,
      numRatings: 231,
      ingredients:
        "Samosas, chickpea curry, yogurt, tamarind chutney, mint chutney, onions, tomatoes, spices",
    },
    {
      id: "c6",
      name: "Sev Puri",
      description:
        "Crispy puris topped with potatoes, onions, chutneys, and sev. A tangy, spicy favorite in Amravati, Maharashtra, perfect for evening snacks.",
      price: 35,
      image: "/placeholder.svg?height=400&width=600&text=Sev+Puri",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.6,
      numRatings: 180,
      ingredients:
        "Puris, potatoes, onions, sev, tamarind chutney, mint chutney, coriander, spices",
    },
    {
      id: "c7",
      name: "Ragda Pattice",
      description:
        "Potato patties topped with white pea curry, chutneys, and sev. A hearty, spicy street food loved in Amravati, Maharashtra.",
      price: 45,
      image: "/placeholder.svg?height=400&width=600&text=Ragda+Pattice",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.0,
      numRatings: 160,
      ingredients:
        "Potato patties, white peas, onions, chutneys, sev, coriander, spices",
    },
    {
      id: "c8",
      name: "Dabeli",
      description:
        "Spicy potato mixture stuffed in a bun, topped with pomegranate, peanuts, and sev. A sweet-spicy treat from Maharashtra, popular in Amravati.",
      price: 30,
      image: "/placeholder.svg?height=400&width=600&text=Dabeli",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "chaat",
      rating: 3.8,
      numRatings: 140,
      ingredients:
        "Bun, potato, dabeli masala, pomegranate, peanuts, sev, chutneys",
    },
    {
      id: "c9",
      name: "Misal Pav",
      description:
        "Spicy sprouted bean curry served with pav, onions, and farsan. A fiery, flavorful breakfast and snack in Amravati, Maharashtra.",
      price: 50,
      image: "/placeholder.svg?height=400&width=600&text=Misal+Pav",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.8,
      numRatings: 220,
      ingredients:
        "Sprouted beans, farsan, onions, pav, lemon, spices, chutneys",
    },
    {
      id: "c10",
      name: "Papdi Chaat",
      description:
        "Crispy papdi, potatoes, chickpeas, yogurt, and chutneys. A refreshing, tangy chaat enjoyed by all ages in Amravati, Maharashtra.",
      price: 40,
      image: "/placeholder.svg?height=400&width=600&text=Papdi+Chaat",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "chaat",
      rating: 4.0,
      numRatings: 150,
      ingredients:
        "Papdi, potatoes, chickpeas, yogurt, tamarind chutney, mint chutney, sev, coriander",
    },
  ],
  rolls: [
    {
      id: "r1",
      name: "Kathi Roll",
      description:
        "Paratha wrapped around spiced chicken or paneer with onions and chutney. A filling, flavorful roll enjoyed by many in Amravati, Maharashtra.",
      price: 80,
      image: "/placeholder.svg?height=400&width=600&text=Kathi+Roll",
      isVegetarian: false,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 4.2,
      numRatings: 198,
      ingredients:
        "Paratha, chicken/paneer, bell peppers, onions, spices, egg, chutneys",
    },
    {
      id: "r2",
      name: "Paneer Tikka Roll",
      description:
        "Soft rumali roti filled with marinated and grilled paneer tikka. A popular vegetarian street roll in Amravati, Maharashtra, known for its smoky, spicy taste.",
      price: 75,
      image: "/placeholder.svg?height=400&width=600&text=Paneer+Tikka+Roll",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 4.3,
      numRatings: 156,
      ingredients:
        "Rumali roti, paneer, yogurt, bell peppers, onions, spices, mint chutney",
    },
    {
      id: "r3",
      name: "Chicken Frankie",
      description:
        "Spiced chicken wrapped in a thin flatbread with special masala. A favorite non-veg street food in Amravati, Maharashtra, loved for its bold flavors.",
      price: 90,
      image: "/placeholder.svg?height=400&width=600&text=Chicken+Frankie",
      isVegetarian: false,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 4.4,
      numRatings: 212,
      ingredients:
        "Flatbread, chicken, onions, bell peppers, spices, frankie masala, chutneys",
    },
    {
      id: "r4",
      name: "Egg Roll",
      description:
        "Soft paratha filled with spiced egg, onions, and chutney. A protein-rich, spicy street roll popular in Amravati, Maharashtra.",
      price: 50,
      image: "/placeholder.svg?height=400&width=600&text=Egg+Roll",
      isVegetarian: false,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 3.9,
      numRatings: 120,
      ingredients: "Paratha, egg, onions, green chilies, spices, chutney",
    },
    {
      id: "r5",
      name: "Veg Frankie",
      description:
        "Thin flatbread filled with spicy mixed vegetables, onions, and sauces. A favorite vegetarian roll in Amravati, Maharashtra, for quick bites.",
      price: 45,
      image: "/placeholder.svg?height=400&width=600&text=Veg+Frankie",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 4.1,
      numRatings: 110,
      ingredients: "Flatbread, mixed vegetables, onions, spices, sauces",
    },
    {
      id: "r6",
      name: "Cheese Corn Roll",
      description:
        "Paratha stuffed with cheesy corn mixture, onions, and spices. A creamy, kid-friendly street roll in Amravati, Maharashtra.",
      price: 60,
      image: "/placeholder.svg?height=400&width=600&text=Cheese+Corn+Roll",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "rolls",
      rating: 3.7,
      numRatings: 90,
      ingredients: "Paratha, cheese, corn, onions, spices",
    },
    {
      id: "r7",
      name: "Mushroom Roll",
      description:
        "Soft roti filled with sautéed mushrooms, onions, and spices. A unique, earthy roll gaining popularity in Amravati, Maharashtra.",
      price: 70,
      image: "/placeholder.svg?height=400&width=600&text=Mushroom+Roll",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 3.5,
      numRatings: 80,
      ingredients: "Roti, mushrooms, onions, bell peppers, spices, chutney",
    },
    {
      id: "r8",
      name: "Paneer Bhurji Roll",
      description:
        "Rumali roti filled with spicy paneer bhurji, onions, and chutney. A protein-packed vegetarian roll in Amravati, Maharashtra.",
      price: 75,
      image: "/placeholder.svg?height=400&width=600&text=Paneer+Bhurji+Roll",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 4.0,
      numRatings: 100,
      ingredients: "Rumali roti, paneer, onions, tomatoes, spices, chutney",
    },
    {
      id: "r9",
      name: "Chicken Tikka Roll",
      description:
        "Paratha filled with juicy chicken tikka, onions, and mint chutney. A spicy, meaty favorite in Amravati, Maharashtra.",
      price: 90,
      image: "/placeholder.svg?height=400&width=600&text=Chicken+Tikka+Roll",
      isVegetarian: false,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 4.5,
      numRatings: 130,
      ingredients: "Paratha, chicken tikka, onions, mint chutney, spices",
    },
    {
      id: "r10",
      name: "Schezwan Veg Roll",
      description:
        "Flatbread filled with spicy Schezwan vegetables, onions, and sauces. A fusion roll loved by spice lovers in Amravati, Maharashtra.",
      price: 55,
      image: "/placeholder.svg?height=400&width=600&text=Schezwan+Veg+Roll",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "rolls",
      rating: 3.8,
      numRatings: 95,
      ingredients:
        "Flatbread, mixed vegetables, Schezwan sauce, onions, spices",
    },
  ],
  curries: [
    {
      id: "cu1",
      name: "Pav Bhaji",
      description:
        "Spicy mashed vegetable curry served with buttered bread rolls. A signature street food of Maharashtra, especially popular in Amravati for its rich, buttery taste.",
      price: 70,
      image: "/placeholder.svg?height=400&width=600&text=Pav+Bhaji",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 4.9,
      numRatings: 267,
      ingredients:
        "Potatoes, peas, tomatoes, onions, bell peppers, pav bhaji masala, butter, bread rolls",
    },
    {
      id: "cu2",
      name: "Chole Bhature",
      description:
        "Spicy chickpea curry served with deep-fried bread. A hearty, satisfying meal found at many street stalls in Amravati, Maharashtra, loved for its bold flavors.",
      price: 80,
      image: "/placeholder.svg?height=400&width=600&text=Chole+Bhature",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 4.3,
      numRatings: 243,
      ingredients:
        "Chickpeas, tomatoes, onions, spices, bhature (deep-fried bread), coriander",
    },
    {
      id: "cu3",
      name: "Vada Pav",
      description:
        "Spicy potato fritter in a bun with chutneys. The iconic street food of Maharashtra, especially beloved in Amravati for its spicy, tangy flavors.",
      price: 25,
      image: "/placeholder.svg?height=400&width=600&text=Vada+Pav",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 4.8,
      numRatings: 289,
      ingredients:
        "Potatoes, gram flour, spices, bread bun, garlic chutney, green chutney",
    },
    {
      id: "cu4",
      name: "Usal Pav",
      description:
        "Spicy sprouted bean curry served with pav, onions, and lemon. A classic Maharashtrian street curry, especially popular in Amravati.",
      price: 40,
      image: "/placeholder.svg?height=400&width=600&text=Usal+Pav",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 4.2,
      numRatings: 110,
      ingredients: "Sprouted beans, onions, tomatoes, pav, lemon, spices",
    },
    {
      id: "cu5",
      name: "Egg Curry",
      description:
        "Boiled eggs cooked in spicy onion-tomato gravy, served with pav or rice. A protein-rich street curry in Amravati, Maharashtra.",
      price: 60,
      image: "/placeholder.svg?height=400&width=600&text=Egg+Curry",
      isVegetarian: false,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 3.7,
      numRatings: 90,
      ingredients: "Eggs, onions, tomatoes, spices, pav/rice",
    },
    {
      id: "cu6",
      name: "Chicken Curry",
      description:
        "Tender chicken pieces cooked in spicy Maharashtrian gravy, served with pav or rice. A non-veg favorite in Amravati.",
      price: 90,
      image: "/placeholder.svg?height=400&width=600&text=Chicken+Curry",
      isVegetarian: false,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 4.4,
      numRatings: 120,
      ingredients: "Chicken, onions, tomatoes, spices, pav/rice",
    },
    {
      id: "cu7",
      name: "Matki Usal",
      description:
        "Matki (moth beans) cooked in spicy gravy, served with pav. A nutritious, protein-rich curry popular in Amravati, Maharashtra.",
      price: 35,
      image: "/placeholder.svg?height=400&width=600&text=Matki+Usal",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 3.8,
      numRatings: 80,
      ingredients: "Matki, onions, tomatoes, spices, pav",
    },
    {
      id: "cu8",
      name: "Paneer Masala",
      description:
        "Paneer cubes cooked in spicy tomato-onion gravy, served with pav or rice. A creamy, vegetarian curry in Amravati, Maharashtra.",
      price: 80,
      image: "/placeholder.svg?height=400&width=600&text=Paneer+Masala",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 4.1,
      numRatings: 100,
      ingredients: "Paneer, onions, tomatoes, spices, pav/rice",
    },
    {
      id: "cu9",
      name: "Chana Masala",
      description:
        "Chickpeas cooked in spicy tomato-onion gravy, served with pav or rice. A filling, vegetarian curry in Amravati, Maharashtra.",
      price: 50,
      image: "/placeholder.svg?height=400&width=600&text=Chana+Masala",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 4.0,
      numRatings: 90,
      ingredients: "Chickpeas, onions, tomatoes, spices, pav/rice",
    },
    {
      id: "cu10",
      name: "Egg Bhurji Pav",
      description:
        "Spicy scrambled eggs served with pav, onions, and lemon. A quick, protein-rich street curry in Amravati, Maharashtra.",
      price: 45,
      image: "/placeholder.svg?height=400&width=600&text=Egg+Bhurji+Pav",
      isVegetarian: false,
      isSpicy: true,
      region: "Maharashtra",
      category: "curries",
      rating: 3.9,
      numRatings: 85,
      ingredients: "Eggs, onions, tomatoes, spices, pav, lemon",
    },
  ],
  sweets: [
    {
      id: "s1",
      name: "Jalebi",
      description:
        "Deep-fried pretzel-shaped sweets soaked in sugar syrup. A festive favorite in Amravati, Maharashtra, enjoyed hot and fresh from local sweet shops.",
      price: 30,
      image: "/placeholder.svg?height=400&width=600&text=Jalebi",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 4.7,
      numRatings: 178,
      ingredients: "All-purpose flour, yogurt, sugar syrup, saffron, cardamom",
    },
    {
      id: "s2",
      name: "Kulfi",
      description:
        "Traditional Indian ice cream in various flavors. A creamy, cooling dessert popular on the streets of Amravati, Maharashtra, especially during summer.",
      price: 35,
      image: "/placeholder.svg?height=400&width=600&text=Kulfi",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 4.5,
      numRatings: 201,
      ingredients: "Milk, sugar, pistachios, almonds, cardamom, saffron",
    },
    {
      id: "s3",
      name: "Gulab Jamun",
      description:
        "Deep-fried milk solids soaked in rose-flavored sugar syrup. A classic sweet treat in Amravati, Maharashtra, perfect for celebrations and special occasions.",
      price: 40,
      image: "/placeholder.svg?height=400&width=600&text=Gulab+Jamun",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 4.8,
      numRatings: 234,
      ingredients:
        "Milk powder, all-purpose flour, sugar syrup, cardamom, rose water",
    },
    {
      id: "s4",
      name: "Shira",
      description:
        "Semolina pudding flavored with cardamom and garnished with nuts. A warm, comforting sweet enjoyed in Amravati, Maharashtra, especially during festivals.",
      price: 20,
      image: "/placeholder.svg?height=400&width=600&text=Shira",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 4.0,
      numRatings: 70,
      ingredients: "Semolina, sugar, ghee, cardamom, nuts",
    },
    {
      id: "s5",
      name: "Puran Poli",
      description:
        "Sweet flatbread stuffed with jaggery and lentil filling. A festive Maharashtrian sweet, especially popular in Amravati during Holi and Ganesh Chaturthi.",
      price: 30,
      image: "/placeholder.svg?height=400&width=600&text=Puran+Poli",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 4.6,
      numRatings: 90,
      ingredients: "Wheat flour, chana dal, jaggery, ghee, cardamom",
    },
    {
      id: "s6",
      name: "Modak",
      description:
        "Steamed rice flour dumplings filled with coconut and jaggery. A traditional sweet offered to Lord Ganesha in Amravati, Maharashtra.",
      price: 25,
      image: "/placeholder.svg?height=400&width=600&text=Modak",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 4.7,
      numRatings: 100,
      ingredients: "Rice flour, coconut, jaggery, cardamom, ghee",
    },
    {
      id: "s7",
      name: "Shrikhand",
      description:
        "Sweetened strained yogurt flavored with cardamom and saffron. A creamy, cooling dessert enjoyed in Amravati, Maharashtra, especially in summer.",
      price: 30,
      image: "/placeholder.svg?height=400&width=600&text=Shrikhand",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 4.3,
      numRatings: 80,
      ingredients: "Yogurt, sugar, cardamom, saffron, nuts",
    },
    {
      id: "s8",
      name: "Basundi",
      description:
        "Thickened sweetened milk flavored with cardamom and garnished with nuts. A rich, festive dessert in Amravati, Maharashtra.",
      price: 35,
      image: "/placeholder.svg?height=400&width=600&text=Basundi",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 4.2,
      numRatings: 85,
      ingredients: "Milk, sugar, cardamom, nuts",
    },
    {
      id: "s9",
      name: "Kharvas",
      description:
        "Milk pudding made from colostrum, flavored with cardamom. A unique, traditional sweet found in Amravati, Maharashtra, during special occasions.",
      price: 40,
      image: "/placeholder.svg?height=400&width=600&text=Kharvas",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 3.7,
      numRatings: 60,
      ingredients: "Colostrum milk, sugar, cardamom",
    },
    {
      id: "s10",
      name: "Anarsa",
      description:
        "Crispy rice flour and jaggery cookies, deep-fried and coated with poppy seeds. A festive treat in Amravati, Maharashtra.",
      price: 30,
      image: "/placeholder.svg?height=400&width=600&text=Anarsa",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "sweets",
      rating: 3.8,
      numRatings: 70,
      ingredients: "Rice flour, jaggery, poppy seeds, ghee",
    },
  ],
  beverages: [
    {
      id: "b1",
      name: "Masala Chai",
      description:
        "Spiced tea with milk and aromatic spices. A comforting beverage enjoyed at every street corner in Amravati, Maharashtra, especially during monsoon season.",
      price: 15,
      image: "/placeholder.svg?height=400&width=600&text=Masala+Chai",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.9,
      numRatings: 312,
      ingredients:
        "Tea leaves, milk, ginger, cardamom, cinnamon, cloves, sugar",
    },
    {
      id: "b2",
      name: "Lassi",
      description:
        "Yogurt-based sweet or savory drink with various flavors. A refreshing, cooling drink popular in Amravati, Maharashtra, especially during the hot summer months.",
      price: 25,
      image: "/placeholder.svg?height=400&width=600&text=Lassi",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.5,
      numRatings: 187,
      ingredients:
        "Yogurt, sugar/salt, water, cardamom, saffron (for sweet lassi)",
    },
    {
      id: "b3",
      name: "Nimbu Pani",
      description:
        "Refreshing lemonade with a hint of salt and spices. A street-side favorite in Amravati, Maharashtra, perfect for quenching thirst on hot days.",
      price: 20,
      image: "/placeholder.svg?height=400&width=600&text=Nimbu+Pani",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.6,
      numRatings: 156,
      ingredients: "Lemon juice, water, sugar, salt, cumin powder, mint leaves",
    },
    {
      id: "b4",
      name: "Rose Milk",
      description:
        "Chilled milk flavored with rose syrup, served over ice. A sweet, refreshing summer drink popular in Amravati, Maharashtra.",
      price: 20,
      image: "/placeholder.svg?height=400&width=600&text=Rose+Milk",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.2,
      numRatings: 80,
      ingredients: "Milk, rose syrup, sugar, ice",
    },
    {
      id: "b5",
      name: "Buttermilk (Chaas)",
      description:
        "Spiced yogurt drink with cumin and coriander, served chilled. A cooling, digestive beverage enjoyed in Amravati, Maharashtra, especially in summer.",
      price: 15,
      image: "/placeholder.svg?height=400&width=600&text=Buttermilk",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.3,
      numRatings: 90,
      ingredients: "Yogurt, water, cumin, coriander, salt",
    },
    {
      id: "b6",
      name: "Cold Coffee",
      description:
        "Chilled coffee blended with milk and sugar, served over ice. A popular, energizing street beverage in Amravati, Maharashtra.",
      price: 30,
      image: "/placeholder.svg?height=400&width=600&text=Cold+Coffee",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.4,
      numRatings: 100,
      ingredients: "Coffee, milk, sugar, ice",
    },
    {
      id: "b7",
      name: "Sugarcane Juice",
      description:
        "Freshly pressed sugarcane juice with lemon and ginger, served chilled. A hydrating, sweet street drink in Amravati, Maharashtra.",
      price: 15,
      image: "/placeholder.svg?height=400&width=600&text=Sugarcane+Juice",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.8,
      numRatings: 120,
      ingredients: "Sugarcane, lemon, ginger, ice",
    },
    {
      id: "b8",
      name: "Falooda",
      description:
        "Sweet, layered dessert drink with vermicelli, basil seeds, rose syrup, and ice cream. A festive favorite in Amravati, Maharashtra.",
      price: 40,
      image: "/placeholder.svg?height=400&width=600&text=Falooda",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.5,
      numRatings: 110,
      ingredients: "Milk, vermicelli, basil seeds, rose syrup, ice cream",
    },
    {
      id: "b9",
      name: "Jaljeera",
      description:
        "Spiced lemonade with cumin, mint, and black salt, served chilled. A tangy, digestive drink popular in Amravati, Maharashtra.",
      price: 15,
      image: "/placeholder.svg?height=400&width=600&text=Jaljeera",
      isVegetarian: true,
      isSpicy: true,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.0,
      numRatings: 90,
      ingredients: "Water, lemon, cumin, mint, black salt, spices",
    },
    {
      id: "b10",
      name: "Badam Milk",
      description:
        "Hot or cold milk flavored with almonds, cardamom, and saffron. A nourishing, festive beverage in Amravati, Maharashtra.",
      price: 25,
      image: "/placeholder.svg?height=400&width=600&text=Badam+Milk",
      isVegetarian: true,
      isSpicy: false,
      region: "Maharashtra",
      category: "beverages",
      rating: 4.1,
      numRatings: 100,
      ingredients: "Milk, almonds, cardamom, saffron, sugar",
    },
  ],
};
